import * as command from "@pulumi/command";
import * as pulumi from "@pulumi/pulumi";
import * as config from "./config";
import * as ssh from "./ssh";
import { resource, shuffle } from "./utils";

export const writePluginBlacklistFile = new command.remote.Command(resource("write-plugin-blacklist-file"), {
    connection: ssh.connection,
    create: pulumi.interpolate`echo -e "${config.game.pluginBlacklist?.join("\n")}" > /root/blacklist.txt`,
    delete: pulumi.interpolate`rm /root/blacklist.txt`,
    triggers: [ssh.connection.host],
});

const availableTracks = [
    "A01-Race.Challenge.Gbx",
    "A02-Race.Challenge.Gbx",
    "A03-Race.Challenge.Gbx",
    "A04-Acrobatic.Challenge.Gbx",
    "A05-Race.Challenge.Gbx",
    "A06-Obstacle.Challenge.Gbx",
    "A07-Race.Challenge.Gbx",
    "A08-Endurance.Challenge.Gbx",
    "A09-Race.Challenge.Gbx",
    "A10-Acrobatic.Challenge.Gbx",
    "A11-Race.Challenge.Gbx",
    "A12-Speed.Challenge.Gbx",
    "A13-Race.Challenge.Gbx",
    "A14-Race.Challenge.Gbx",
    "A15-Speed.Challenge.Gbx",
    "B01-Race.Challenge.Gbx",
    "B02-Race.Challenge.Gbx",
    "B03-Race.Challenge.Gbx",
    "B04-Acrobatic.Challenge.Gbx",
    "B05-Race.Challenge.Gbx",
    "B06-Obstacle.Challenge.Gbx",
    "B07-Race.Challenge.Gbx",
    "B08-Endurance.Challenge.Gbx",
    "B09-Acrobatic.Challenge.Gbx",
    "B10-Speed.Challenge.Gbx",
    "B11-Race.Challenge.Gbx",
    "B12-Race.Challenge.Gbx",
    "B13-Obstacle.Challenge.Gbx",
    "B14-Speed.Challenge.Gbx",
    "B15-Race.Challenge.Gbx",
    "C01-Race.Challenge.Gbx",
    "C02-Race.Challenge.Gbx",
    "C03-Acrobatic.Challenge.Gbx",
    "C04-Race.Challenge.Gbx",
    "C05-Endurance.Challenge.Gbx",
    "C06-Speed.Challenge.Gbx",
    "C07-Race.Challenge.Gbx",
    "C08-Obstacle.Challenge.Gbx",
    "C09-Race.Challenge.Gbx",
    "C10-Acrobatic.Challenge.Gbx",
    "C11-Race.Challenge.Gbx",
    "C12-Obstacle.Challenge.Gbx",
    "C13-Race.Challenge.Gbx",
    "C14-Endurance.Challenge.Gbx",
    "C15-Speed.Challenge.Gbx",
    "D01-endurance.Challenge.Gbx",
    "D02-Race.Challenge.Gbx",
    "D03-Acrobatic.Challenge.Gbx",
    "D04-Race.Challenge.Gbx",
    "D05-Race.Challenge.Gbx",
    "D06-Obstacle.Challenge.Gbx",
    "D07-Race.Challenge.Gbx",
    "D08-Speed.Challenge.Gbx",
    "D09-obstacle.Challenge.Gbx",
    "D10-Race.Challenge.Gbx",
    "D11-Acrobatic.Challenge.Gbx",
    "D12-Speed.Challenge.Gbx",
    "D13-Race.Challenge.Gbx",
    "D14-Endurance.Challenge.Gbx",
    "D15-Endurance.Challenge.Gbx",
    "E01-Obstacle.Challenge.Gbx",
    "E02-Endurance.Challenge.Gbx",
    "E03-Endurance.Challenge.Gbx",
    "E04-Obstacle.Challenge.Gbx",
    "E05-Endurance.Challenge.Gbx",
].map(t => `Challenges/Nadeo/${t}`);

export const writeTrackPlaylistFile = new command.remote.Command(resource("write-track-playlist-file"), {
    connection: ssh.connection,
    create: pulumi.interpolate`echo -e "${shuffle(availableTracks).slice(0, 20).join("\n")}" > /root/playlist.txt`,
    delete: pulumi.interpolate`rm /root/playlist.txt`,
    triggers: [ssh.connection.host],
});
